[build]
    publish="/public"

[[edge_functions]]
    path="/createRecipe"
    function="createRecipe"
    
[functions]
    deno_import_map = "./imports.json"

[[redirects]]
    to="/.netlify/functions/api/:splat"
    from="/*"
    status=200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"